### ISSUE TITLE
consultation on code

### ISSUE THREAD

**Issue by mafangniu** [huixiancheng/TransRVNet#1]
Thank you for your excellent work！
Do you have a plan to open source? And if so, when will you open source rencently？

**Comment by huixiancheng** [comment]
Because this work is done around the end of 20 and early 21, the code is more confusing and bloated, clean up more trouble, and may not consider open source. But I have update code of the model, you can refer to it.
By the way, since this is work done when I first started doing research, the whole network is heavily overstitched and may not be particularly reference-worthy. 
If you want to try to do range view segmentation with VIT, you can refer to the more insightful [RangeViT](https://github.com/valeoai/rangevit)

**Comment by mafangniu** [comment]
> Because this work is done around the end of 20 and early 21, the code is more confusing and bloated, clean up more trouble, and may not consider open source. But I have update code of the model, you can refer to it. By the way, since this is work done when I first started doing research, the whole network is heavily overstitched and may not be particularly reference-worthy. If you want to try to do range view segmentation with VIT, you can refer to the more insightful [RangeViT](https://github.com/valeoai/rangevit)

**Comment by mafangniu** [comment]
Thx for your reply and suggestion very much, it's very useful
